# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9768c84037df42984740784629c31ba1551e66d2d32ccce7c81694579e07724668de4940833e60cbd56ba41b5f6acd08605aad64d4dce7b4c6eee5b1723fd07

test:
  secret_key_base: 766216124a9d32df58b9247c1cbd8633627b1dea22a03e22b2f777be0ea25060d6e993ae7b71285c20ea13bbc89cd1a75e6d0315302433b74263ae58e8b9fbd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
